-- Lobby
--SMODS.Sound {
    --key = "music_g--iftshop",
    --path = "lobby/brawl_themepark_menu_01.ogg",
    --sync = {
        --['music2'] = true,
        --['music3'] = true,
        --['music4'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.custom_shop_music then
            --return G.STATE == G.STATES.SHOP or G.STATE == G.STATES.--SMODS_BOOSTER_OPENED or G.STATE == G.STATES.--SMODS_REDEEM_VOUCHER
        --end
    --end,
--}

-- having both run shop and menu options at the same time break the sound from running
--SMODS.Sound {
    --key = "music_g--iftshop2",
    --path = "lobby/brawl_themepark_menu_01.ogg",
    --sync = {
        --['music2'] = true,
        --['music3'] = true,
        --['music4'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "G--ift Shop" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_classic",
    --path = "lobby/brawl_stars_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Classic" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_beta",
    --path = "lobby/brawl_original_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Beta" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_hub",
    --path = "lobby/brawl_mystery_02.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Starr Hub" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_retropolis",
    --path = "lobby/brawl_retro_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Retropolis" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_stunt_show",
    --path = "lobby/stuntbrawl_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Stunt Show" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_wasteland",
    --path = "lobby/wasteland_menu_muzak_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Ranger Ranch" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_western",
    --path = "lobby/action_western_stars_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Goldarm Gang" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_mortuary",
    --path = "lobby/brawloween_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Mortis Mortuary" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_ghost_station",
    --path = "lobby/brawloween_2022_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Ghost Station" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_swap_of_love_1",
    --path = "lobby/love_swamp_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Swamp of Love (1)" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_swap_of_love_2",
    --path = "lobby/love_swamp_menu_02.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Swamp of Love (2)" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_alli",
    --path = "lobby/alli_menu_track_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Alli Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_rumble_jungle",
    --path = "lobby/brawl_jungle_menu_music_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Rumble Jungle" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_biodome",
    --path = "lobby/biodome_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Biodome" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_darryl_brawliday",
    --path = "lobby/brawl_pirate_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Darryl's Ship" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_cursed_pirate",
    --path = "lobby/brawl_cursed_pirate_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Cursed Pirate" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_brawzaar",
    --path = "lobby/brawzaar_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Mystic Wanderers" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_snowtel",
    --path = "lobby/snowtel_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Snowtel" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_mexico",
    --path = "lobby/primo_fire_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Mexico" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_brawlywood",
    --path = "lobby/brawlywood_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Starr Studio" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_toon",
    --path = "lobby/starrtoonstudios_menu_music.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Starr Toon" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_castle",
    --path = "lobby/brawl_onceupon_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Castle Courtyard" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_candy",
    --path = "lobby/mandy_candy_meny_muzak_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Candy Land" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

 --SMODS.Sound {
    --key = "music_menu_enchanted_woods",
    --path = "lobby/brawl_enchanted_forest_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Enchanted Woods" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_trunk",
    --path = "lobby/trunk_menu_track_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Trunk Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_space",
    --path = "lobby/military_lase_tag_ingame_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Starr Force" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_city",
    --path = "lobby/bm_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Super City" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_virus",
    --path = "lobby/brawlcade_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Starrcade" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_sea",
    --path = "lobby/deepsea_brawl_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Deep Sea" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_velocirapids",
    --path = "lobby/brawl__jurassic_splash_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Velocirapids" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_pee",
    --path = "lobby/pierce_menu_01.mp3",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Pierce Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_glowbert",
    --path = "lobby/glowbert_menu_01.mp3",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Glowbert Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_glowbert2",
    --path = "lobby/glowbert_menu_02.mp3",
    --sync = {
        --['music1'] = true,
    --},
    --pitch = 1,
    --vol = 0.5,
    --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Sea Monsters Aquarium" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_finx",
    --path = "lobby/finx_menu_music_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Finx Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_kingdom",
    --path = "lobby/feudal_japan_menu_music_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Katana Kingdom" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_katana",
    --path = "lobby/katana_brawl_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Kenji Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_geisha",
    --path = "lobby/kaze_kotomi_menu_music_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Kaze Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_kpop",
    --path = "lobby/kpop_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Melodie Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_work",
    --path = "lobby/jae_edmtrot_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Jae-Yong EDM" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_party",
    --path = "lobby/jae_love_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Jae-Yong Love" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_sk8",
    --path = "lobby/skatebeat_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Sk8 Beat" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_brazil",
    --path = "lobby/mina_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Mina Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_french",
    --path = "lobby/circus_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Bizarre Circus" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_cajun",
    --path = "lobby/juju_menu_loop.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Oddity Shop" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_creepy",
    --path = "lobby/gigi_menu_muzak_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Gigi Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_mad_and_evil",
    --path = "lobby/brawlstars_metal_menu_master_v1.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Madevil Manor" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_BOOOOOM",
    --path = "lobby/brawl_lumi_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Lumi Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}

--SMODS.Sound {
    --key = "music_menu_ziggitysigginy",
    --path = "lobby/ziggy_menu_01.ogg",
    --sync = {
        --['music1'] = true,
    --},
        --pitch = 1,
        --vol = 0.5,
            --select_music_track = function(self)
        --if Brawlatro.config.brawl_menu.option_value == "Ziggy Release" then
            --return G.STAGE == G.STAGES.MAIN_MENU and Brawlatro.config.custom_menu_music
        --end
    --end,
--}